### ISSUE TITLE
no five card trick

### ISSUE THREAD

**Issue by JTBlakey** [JTBlakey/Blackjaques#10]
I don't think there is a five card trick in the game at the moment :(

**Comment by RoseApollo** [comment]
yeah, definitely missing.

will fix tomorrow

**Comment by JTBlakey** [comment]
> 

damn i wasnt expecting you to reply on christmas ngl

**Comment by RoseApollo** [comment]
Holidays come and go, but the daily grind never stops

**Comment by RoseApollo** [comment]
fixed issue in pr #11

**Comment by RoseApollo** [comment]
this can be closed now
