### ISSUE TITLE
Betting

### ISSUE THREAD

**Issue by RoseApollo** [JTBlakey/Blackjaques#4]
i wish to bet money in this game.

Elija plz fix

**Comment by ElijahMMiller** [comment]
L bozo

**Comment by RoseApollo** [comment]
Have implemented basic betting in my fork, will pr later when finalised some other changes

**Comment by RoseApollo** [comment]
fixed in pr #12

**Comment by AUnicornWithNoLife** [comment]
fixed in pr #12
